INSERT INTO tipo_alimento (nombre)
VALUES ('VALOR NUTRICIONAL'), --id puede ser 1
('INGESTA RECOMENDADAS Y OBJETIVOS NUTRICIONALES'), --2
('RACIONES Y MEDIDAS CASERAS'), --3
('PATOLOGÍAS Y FISIOLOGÍAS'), --4
('MÉTODOS DE ANÁLISIS'), --5
('CURIOSIDADES'); --6